{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_release",
    "version": "0.0.1-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-9064459a8b0dcd32877107f6002cc429a71659d1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-0.0.1-rc1.aar",
          "url": "flutter_secure_storage_release-0.0.1-rc1.aar",
          "size": 26340,
          "sha512": "b7107d9fa3fc57aa0890316a785667154efb8f3df604262054c3911ea11886f3068f6adba87555046df2ccbdf0ac34c61bc13aa11d290e9cf6eeefeb29de80ff",
          "sha256": "68297807dfc2b1a10faf536957bc8bffa480580873df6314db9b1180e8a992a5",
          "sha1": "f8eb8b9b2cb5aae8fba0ce423ee082ab952b686a",
          "md5": "84a9fe64f92fdce56ae77dab157eccb0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-9064459a8b0dcd32877107f6002cc429a71659d1"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-0.0.1-rc1.aar",
          "url": "flutter_secure_storage_release-0.0.1-rc1.aar",
          "size": 26340,
          "sha512": "b7107d9fa3fc57aa0890316a785667154efb8f3df604262054c3911ea11886f3068f6adba87555046df2ccbdf0ac34c61bc13aa11d290e9cf6eeefeb29de80ff",
          "sha256": "68297807dfc2b1a10faf536957bc8bffa480580873df6314db9b1180e8a992a5",
          "sha1": "f8eb8b9b2cb5aae8fba0ce423ee082ab952b686a",
          "md5": "84a9fe64f92fdce56ae77dab157eccb0"
        }
      ]
    }
  ]
}
